ds<-read.table('/Users/dnes/Downloads/household_power_consumption.txt', header=TRUE, sep=";", stringsAsFactors=FALSE,  dec=".")
subds<- subset(ds, (ds$Date == "1/2/2007" | ds$Date== "2/2/2007"))
dt <- strptime(paste(subds$Date, subds$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
gap <- as.numeric(subds$Global_active_power)
subm1 <- as.numeric(subds$Sub_metering_1)
subm2 <- as.numeric(subds$Sub_metering_2)
subm3 <- as.numeric(subds$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(dt, subm1, type="l", ylab="Energy Submetering", xlab="")
lines(dt, subm2, type="l", col="red")
lines(dt, subm3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"))
dev.off()